name: bugtracker

on:
  issues:
    types: [opened]

jobs:
  issue-job:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
      GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Files
        run: ls -la

      - name: Show Issue Details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"

      - name: Run Agent
        run: python agent.py
